service: sls-graphql-test01

frameworkVersion: "2"

# plugins:
#    - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get

# custom:
  # appSync:
  #   name:  appsync-backend-test01
  #   authenticationType: AMAZON_COGNITO_USER_POOLS
  #   userPoolConfig:
  #     awsRegion: us-east-1
  #     defaultAction: ALLOW
  #     userPoolId: !Ref CognitoUserPool
  #   schema: schema.graphql
  #   mappingTemplatesLocation: mapping-templates
  #   mappingTemplates:
  #     - type: Query
  #       field: getItemsTable
  #       dataSource: ItemsTable

  # dataSources:
  #   - type: NONE
  #     name: none
  #   - type: AMAZON_DYNAMODB
  #     name: ItemsTable
  #     config:
  #       tableName: !Ref ItemsTable

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: title
            AttributeType: S
        Tags:
          - Key: Name
            Value: items-table

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true

    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED